### ISSUE TITLE
CORS 문제 - 모바일에서 보낸 요청 백엔드에서 거절당하는 문제

### ISSUE THREAD

**Issue by hanslelee** [Hi-DN/navada-backend#23]
## 이슈 설명
flutter에서 백엔드로 보낸 api 요청을 거절당하는 문제를 해결하지 못해 어려움을 겪고 있습니다 ㅠ.ㅠ 
조언해주시면 넘넘 감사하겠습니다. @minji1110 

## 이슈 상세 내용
httpclient를 작성하면서 테스트 하려고 상품 단건 조회를 불렀을 때 다음과 같은 오류가 납니다.
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/51855129/180174019-849d170c-bab6-4c01-8281-4e690cc78682.png">

백엔드엔 webconfig를 다음과 같이 설정해 두었습니다.
<img width="898" alt="image" src="https://user-images.githubusercontent.com/51855129/180174806-3a67abfd-04a6-496d-8a19-d8ab021672e1.png">

**Comment by minji1110** [comment]
이렇게만 봐서는 저도 잘 모르겠는데.. 백앤드에서도 오류가 뜨나요?

**Comment by minji1110** [comment]
주소 설정을 혹시 어떻게 하셨나여..?!

**Comment by hanslelee** [comment]
백엔드에선 오류 안뜨고 모바일에서만 뜹니다!
이렇게 세가지 해봤는데 다 안되네요..ㅠ.ㅠ
<img width="482" alt="image" src="https://user-images.githubusercontent.com/51855129/180183938-611f1889-0ea5-43f8-a6e3-03e899651872.png">

푸시할테니 같이 봐주실래요??ㅠ0ㅠ

**Comment by minji1110** [comment]
네넵 8000은 한슬님이 포트 따로 설정해두신건가요?
일단 푸시 해주세요!

**Comment by hanslelee** [comment]
헐....

**Comment by hanslelee** [comment]
저 8080이라 해놓은줄 알았네요 어제부터 삽질했네.... 8080으로 바꾸니까 잘 되네요...ㅎㅎㅎㅏ... 감사합니다 민지님...😭😭😭

**Comment by minji1110** [comment]
오마이갓...

**Comment by minji1110** [comment]
화가 많이 나시겠는데요...ㅠㅠ 고생하셨어요..
