### ISSUE TITLE
@ModelAttribute vs @RequestBody

### ISSUE THREAD

**Issue by hanslelee** [Hi-DN/navada-backend#27]
모바일에서 상품등록 api를 테스트하는데, 계속 다음과 같은 에러가 발생했습니다.
<img width="809" alt="image" src="https://user-images.githubusercontent.com/51855129/181216302-2edfe42b-163a-48c5-a028-6aacd8ed1215.png">
서버에서 확인해보니 파라미터들로 null이 넘어오더라구용

찾아보니 `@ModelAttribute`와 `@RequestBody`의 차이로 인한 문제였던 것 같습니다. [참고](https://dionysus2074.tistory.com/172)
원격진료 플젝에서 사용한 방식은 모두 `@RequestBody`에 적용되는? 방식이라 모바일에서 오류가 났던 것 같아서
ProductController에서 `@ModelAttribute` -> `@RequestBody`로 바꿨더니 작동이 잘 됐습니당

해물사에선 어떻게 하셨었나요?!
`@ModelAttribute` -> `@RequestBody`로 백엔드에서 수정하는 게 나을까요, 아니면 다른 방법으로 해결하는 게 나을까요??

**Comment by minji1110** [comment]
해물사에서는 `@ModelAttribute` 사용했었는데 `@RequestBody` 사용해도 문제가 없으면 그렇게 해도 될 것 같아요! 
지금 뜨는 null 문제는 ProductParams에 categoryId 타입을 Long 말고 long으로 바꿔도 해결되는 걸로 보이는데 
그냥 더 편하다고 생각하시는 방법 사용해도 좋을 것 같습니다!

**Comment by hanslelee** [comment]
엇 제거에서는 왜 안될까요?ㅠㅜㅜ long으로 바꾸고
모바일에서 이렇게 설정하고 요청 보냈는데
<img width="351" alt="image" src="https://user-images.githubusercontent.com/51855129/181878571-0790b45c-d595-4131-b7f6-7715219a091c.png">

`@ModelAttribute`사용시 백엔드의 상품 등록 api 에서 넘어오는 파라미터 출력해보니
<img width="908" alt="image" src="https://user-images.githubusercontent.com/51855129/181878518-246ffa19-7687-44ea-baab-d8c21f636b7e.png">
이렇게 나오는 것 같아요... 다른것들도 안오는것같은데 제거에서만 그런건가요???ㅠㅠ

**Comment by minji1110** [comment]
흠.. 저는 postman으로 테스트해본거라 모바일에서 보내면 세팅값이 좀 달라져서 그런걸까요..?
일단은 작동이 되야하니까 `@RequestBody`로 바꾸고 진행하실래요..?!

**Comment by hanslelee** [comment]
흠 그러게요...ㅠ0ㅠ 네 알겠습니당 그럼 일단 일괄 수정해서 머지해놓을게요!
