### ISSUE TITLE
@PatchMapping or @PostMapping

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/navada-backend#41]
<img width="851" alt="스크린샷 2022-09-22 오후 11 31 54" src="https://user-images.githubusercontent.com/70498432/191776074-441c9a4f-de64-4abc-be50-738a1fbc821f.png">

현재 다음과 같이 @PatchMapping으로 정의된 교환수락 api가 있습니다. 

<img width="509" alt="스크린샷 2022-09-22 오후 11 32 11" src="https://user-images.githubusercontent.com/70498432/191776094-4876f140-d9bd-4ac9-affd-0b9ecd99fb44.png">

교환신청인 Request 엔티티 기준으로는 데이터가 일부 수정되므로 Patch 가 맞지만, 두번째사진과 같이 내부에서 다른 엔티티(Exchange)를 save 하고, 해당 엔티티를 반환하고 있습니다.
이 경우 Patch와 Post중 어느것을 선택하는게 맞을까요? 저는 Post가 더 적합하다고 생각하는데 의견이 어떠신지 물어보고 싶습니다!

**Comment by hanslelee** [comment]
저도 Post가 더 알맞은 것 같다는 생각이 드네요! 발견 감사합니다 ㅎㅎㅎ
그런데 post로 변경할 시 api를 request가 아닌 exchange쪽에 두어야 할까요?!

**Comment by minji1110** [comment]
뭐가 좋을까요? 교환수락한 후에 엔티티 생성되는거라 아예 교환으로 이동해도 뭔가 이상할것 같은데..
저는 그냥 두어도 괜찮을것 같은데 어떠세요?!
아니면 createExchange 를 RequestService 로 가져오는건 이상하려나요..?

**Comment by hanslelee** [comment]
엄... 그러게요 createExchange는 ExchangeService에 있는게 나을 것 같긴한데...
저도 그냥 두어도 좋을것 같아요! 그럼 post로 변경만 하는걸로 할까요?!

**Comment by minji1110** [comment]
> 엄... 그러게요 createExchange는 ExchangeService에 있는게 나을 것 같긴한데... 저도 그냥 두어도 좋을것 같아요! 그럼 post로 변경만 하는걸로 할까요?!

저번에 제가 그쪽 작동이 잘 안되서 그부분때문인가 하고 고쳐봤었거든요 그래서 아마 지금 @PostMapping으로 남아잇는 것 같아요! 그럼 그렇게 두는걸로 하겠습니다!
