### ISSUE TITLE
교환 취소 알림 전송 시 취소자 정보에 대하여

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/navada-backend#57]
@hanslelee 현재 백앤드에서 교환 취소 알림 전송 기능을 개발하려고 하는데,
Exchange 엔티티 내에 취소자 정보가 존재하지 않습니다. 따라서 이와 관련해서 어떻게 처리하는게 좋을지 의견 구합니다!

(1) uri 수정
기존 : /exchange/{exchangeId}/cancel
수정 : /user/{userId}/exchange/{exchangeId}/cancel

(2) isAcceptor 파라미터 추가

본인 물품이 accept쪽인지 request쪽인지 확인하는 작업이 (1)은 백앤드에서, (2)는 모바일에서 이루어지는 차이일 것 같은데,, 어느쪽이 더 나아보이시나요?
저는 작업하기에는 (1)이 더 수월할 것 같긴한데 잘 모르겠어서 의견 여쭙니다!
아니면 또다른 의견이 있다면 제시 부탁드립니당 ~@!

**Comment by minji1110** [comment]
아니면,
(3) 양쪽 모두에 '투썸 아아'와 '스벅 아아' 에 대한 교환이 취소처리되었습니다.  보내기 
-> 이건 취소당한입장이 좀 당황스러우려나요?

**Comment by hanslelee** [comment]
@minji1110 제가 생각했을 때도 1번이 나을 것 같습니다! 3번도 좋은데 말씀해주신 것처럼 취소당한 입장이 좀 당황스러울 수도 있을 것 같아 조심스럽네요 😂🤣🤣

**Comment by minji1110** [comment]
@hanslelee 넹 그럼 1번으로 수정하겠습니다! 🤓
